# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-17 03:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('UserAccess', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuildType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=200, unique=True, verbose_name='\u5206\u7c7b\u540d\u79f0')),
                ('desc', models.CharField(blank=True, max_length=500, null=True, verbose_name='\u5206\u7c7b\u63cf\u8ff0')),
            ],
            options={
                'verbose_name': '\u56e2\u961f\u5efa\u8bbe\u5206\u7c7b',
                'verbose_name_plural': '\u56e2\u961f\u5efa\u8bbe\u5206\u7c7b\u7ba1\u7406',
            },
        ),
        migrations.CreateModel(
            name='DatePeriod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='\u5f00\u59cb\u65e5\u671f')),
                ('end_date', models.DateField(verbose_name='\u7ed3\u675f\u65e5\u671f')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
            ],
            options={
                'ordering': ['-start_date'],
                'verbose_name': '\u65f6\u95f4\u5468\u671f',
                'verbose_name_plural': '\u65f6\u95f4\u5468\u671f\u7ba1\u7406',
            },
        ),
        migrations.CreateModel(
            name='JobCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=200, unique=True, verbose_name='\u5de5\u4f5c\u7f16\u53f7')),
                ('job_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='\u5de5\u4f5c\u540d\u79f0')),
                ('old_code', models.CharField(blank=True, max_length=200, null=True, verbose_name='\u65e7\u7248\u7f16\u53f7')),
                ('jf', models.CharField(blank=True, max_length=200, null=True, verbose_name='\u7532\u65b9')),
                ('jf_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='\u7532\u65b9\u5355\u4f4d\u540d\u79f0')),
                ('person_in_charge', models.CharField(default='\u672a\u5b9a', max_length=200, verbose_name='\u6211\u65b9\u8d1f\u8d23\u4eba')),
                ('desc', models.TextField(blank=True, null=True, verbose_name='\u5de5\u4f5c\u63cf\u8ff0')),
            ],
            options={
                'verbose_name': '\u5de5\u4f5c\u7f16\u53f7',
                'verbose_name_plural': '\u5de5\u4f5c\u7f16\u53f7\u7ba1\u7406',
            },
        ),
        migrations.CreateModel(
            name='JobStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=200, unique=True, verbose_name='\u8fdb\u5c55\u72b6\u6001')),
                ('desc', models.TextField(blank=True, null=True, verbose_name='\u72b6\u6001\u63cf\u8ff0')),
            ],
            options={
                'verbose_name': '\u8fdb\u5c55\u72b6\u6001',
                'verbose_name_plural': '\u8fdb\u5c55\u72b6\u6001\u7ba1\u7406',
            },
        ),
        migrations.CreateModel(
            name='JobType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='\u5de5\u4f5c\u7c7b\u522b')),
                ('desc', models.TextField(blank=True, null=True, verbose_name='\u7c7b\u522b\u63cf\u8ff0')),
            ],
            options={
                'verbose_name': '\u5de5\u4f5c\u7c7b\u522b',
                'verbose_name_plural': '\u5de5\u4f5c\u7c7b\u522b\u7ba1\u7406',
            },
        ),
        migrations.CreateModel(
            name='PersonalReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_date', models.DateField(verbose_name='\u65e5\u671f')),
                ('job_time', models.FloatField(verbose_name='\u5de5\u65f6/\u4eba\u529b')),
                ('job_content', models.CharField(max_length=1000, verbose_name='\u5de5\u4f5c\u5185\u5bb9')),
                ('job_block', models.CharField(blank=True, max_length=1000, null=True, verbose_name='\u5de5\u4f5c\u963b\u788d')),
                ('job_opinion', models.CharField(blank=True, max_length=500, null=True, verbose_name='\u8d1f\u8d23\u4eba\u5ba1\u6279\u610f\u89c1')),
                ('job_plan', models.CharField(blank=True, max_length=1000, null=True, verbose_name='\u660e\u65e5\u8ba1\u5212')),
                ('delete_status', models.BooleanField(default=False, verbose_name='\u5220\u9664\u72b6\u6001')),
                ('remark', models.CharField(blank=True, max_length=500, null=True, verbose_name='\u5907\u6ce8')),
                ('date_period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WeeklyReport.DatePeriod', verbose_name='\u65f6\u95f4\u5468\u671f')),
                ('depart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserAccess.Department', verbose_name='\u6240\u5c5e\u90e8\u95e8')),
                ('job_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WeeklyReport.JobCode', verbose_name='\u5de5\u4f5c\u7f16\u53f7')),
                ('job_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WeeklyReport.JobStatus', verbose_name='\u8fdb\u5c55\u72b6\u6001')),
                ('job_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WeeklyReport.JobType', verbose_name='\u5de5\u4f5c\u7c7b\u522b')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserAccess.MyUser', verbose_name='\u59d3\u540d')),
            ],
            options={
                'ordering': ['-job_date'],
                'verbose_name': '\u4e2a\u4eba\u5468\u62a5',
                'verbose_name_plural': '\u4e2a\u4eba\u5468\u62a5\u7ba1\u7406',
            },
        ),
        migrations.CreateModel(
            name='PlanReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_date', models.DateField(verbose_name='\u65e5\u671f')),
                ('job_time', models.FloatField(verbose_name='\u5de5\u65f6/\u4eba\u529b')),
                ('job_content', models.CharField(max_length=1000, verbose_name='\u5de5\u4f5c\u5185\u5bb9')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='\u8ba1\u5212\u5f00\u59cb\u65e5\u671f')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='\u8ba1\u5212\u5b8c\u6210\u65e5\u671f')),
                ('start_date_r', models.DateField(blank=True, null=True, verbose_name='\u5b9e\u9645\u5f00\u59cb\u65e5\u671f')),
                ('end_date_r', models.DateField(blank=True, null=True, verbose_name='\u5b9e\u9645\u5b8c\u6210\u65e5\u671f')),
                ('remark', models.CharField(blank=True, max_length=500, null=True, verbose_name='\u5907\u6ce8')),
                ('date_period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WeeklyReport.DatePeriod', verbose_name='\u65f6\u95f4\u5468\u671f')),
                ('depart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserAccess.Department', verbose_name='\u6240\u5c5e\u90e8\u95e8')),
                ('job_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WeeklyReport.JobCode', verbose_name='\u5de5\u4f5c\u7f16\u53f7')),
                ('job_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WeeklyReport.JobStatus', verbose_name='\u8fdb\u5c55\u72b6\u6001')),
                ('job_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WeeklyReport.JobType', verbose_name='\u5de5\u4f5c\u7c7b\u522b')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserAccess.MyUser', verbose_name='\u59d3\u540d')),
            ],
            options={
                'verbose_name': '\u4e0b\u5468\u8ba1\u5212',
                'verbose_name_plural': '\u4e0b\u5468\u8ba1\u5212\u7ba1\u7406',
            },
        ),
        migrations.CreateModel(
            name='ProductDevelopment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_goal', models.CharField(max_length=500, verbose_name='\u5de5\u4f5c\u76ee\u6807')),
                ('job_content', models.CharField(max_length=500, verbose_name='\u5de5\u4f5c\u5185\u5bb9')),
                ('summarize', models.CharField(max_length=5000, verbose_name='\u5de5\u4f5c\u603b\u7ed3')),
                ('next_week_plan', models.CharField(blank=True, max_length=500, null=True, verbose_name='\u4e0b\u5468\u8ba1\u5212')),
                ('stage_plan', models.CharField(blank=True, max_length=500, null=True, verbose_name='\u603b\u4f53\u9636\u6bb5\u6027\u8ba1\u5212')),
                ('remark', models.CharField(blank=True, max_length=500, null=True, verbose_name='\u7279\u6b8a\u8bf4\u660e')),
                ('date_period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WeeklyReport.DatePeriod', verbose_name='\u65f6\u95f4\u5468\u671f')),
                ('depart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserAccess.Department', verbose_name='\u6240\u5c5e\u90e8\u95e8')),
            ],
            options={
                'verbose_name': '\u4ea7\u54c1\u7814\u53d1\u8bb0\u5f55',
                'verbose_name_plural': '\u4ea7\u54c1\u7814\u53d1\u7ba1\u7406',
            },
        ),
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=200, unique=True, verbose_name='\u4ea7\u54c1\u5206\u7c7b\u540d\u79f0')),
                ('desc', models.CharField(blank=True, max_length=500, null=True, verbose_name='\u5206\u7c7b\u63cf\u8ff0')),
            ],
            options={
                'verbose_name': '\u4ea7\u54c1\u5206\u7c7b',
                'verbose_name_plural': '\u4ea7\u54c1\u5206\u7c7b\u7ba1\u7406',
            },
        ),
        migrations.CreateModel(
            name='ProjectStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=200, unique=True, verbose_name='\u8fdb\u5c55\u72b6\u6001')),
                ('desc', models.TextField(blank=True, null=True, verbose_name='\u72b6\u6001\u63cf\u8ff0')),
            ],
            options={
                'verbose_name': '\u9879\u76ee\u8fdb\u5c55\u72b6\u6001',
                'verbose_name_plural': '\u9879\u76ee\u8fdb\u5c55\u72b6\u6001\u7ba1\u7406',
            },
        ),
        migrations.CreateModel(
            name='SellProject',
            fields=[
                ('s_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID')),
                ('project_content', models.CharField(max_length=500, verbose_name='\u9879\u76ee\u5185\u5bb9\u7b80\u4ecb')),
                ('job_date', models.DateField(verbose_name='\u65e5\u671f')),
                ('next_week_plan', models.CharField(blank=True, max_length=500, null=True, verbose_name='\u4e0b\u5468\u8ba1\u5212')),
                ('stage_plan', models.CharField(blank=True, max_length=500, null=True, verbose_name='\u603b\u4f53\u9636\u6bb5\u6027\u8ba1\u5212')),
                ('remark', models.CharField(blank=True, max_length=500, null=True, verbose_name='\u7279\u6b8a\u8bf4\u660e')),
                ('date_period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WeeklyReport.DatePeriod', verbose_name='\u65f6\u95f4\u5468\u671f')),
                ('depart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserAccess.Department', verbose_name='\u6240\u5c5e\u90e8\u95e8')),
                ('job_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WeeklyReport.JobCode', verbose_name='\u9879\u76ee\u7f16\u53f7')),
                ('job_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WeeklyReport.JobStatus', verbose_name='\u8fdb\u5c55\u72b6\u6001')),
                ('job_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WeeklyReport.JobType', verbose_name='\u5de5\u4f5c\u7c7b\u578b')),
            ],
            options={
                'verbose_name': '\u9500\u552e\u4e0e\u9879\u76ee\u8bb0\u5f55',
                'verbose_name_plural': '\u9500\u552e\u4e0e\u9879\u76ee\u7ba1\u7406',
            },
        ),
        migrations.CreateModel(
            name='StrategicDeployment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_name', models.CharField(max_length=500, verbose_name='\u5de5\u4f5c\u540d\u79f0')),
                ('job_goal', models.CharField(max_length=500, verbose_name='\u5de5\u4f5c\u76ee\u6807')),
                ('job_content', models.CharField(max_length=500, verbose_name='\u5de5\u4f5c\u5185\u5bb9')),
                ('summarize', models.CharField(max_length=5000, verbose_name='\u5de5\u4f5c\u603b\u7ed3')),
                ('next_week_plan', models.CharField(blank=True, max_length=500, null=True, verbose_name='\u4e0b\u5468\u8ba1\u5212')),
                ('stage_plan', models.CharField(blank=True, max_length=500, null=True, verbose_name='\u9636\u6bb5\u6027\u8ba1\u5212')),
                ('remark', models.CharField(blank=True, max_length=500, null=True, verbose_name='\u7279\u6b8a\u8bf4\u660e')),
                ('date_period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WeeklyReport.DatePeriod', verbose_name='\u65f6\u95f4\u5468\u671f')),
                ('depart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserAccess.Department', verbose_name='\u6240\u5c5e\u90e8\u95e8')),
            ],
            options={
                'verbose_name': '\u6218\u7565\u90e8\u7f72',
                'verbose_name_plural': '\u6218\u7565\u90e8\u7f72\u7ba1\u7406',
            },
        ),
        migrations.CreateModel(
            name='SubBuildType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_type_name', models.CharField(max_length=200, unique=True, verbose_name='\u5b50\u5206\u7c7b\u540d\u79f0')),
                ('desc', models.CharField(blank=True, max_length=500, null=True, verbose_name='\u5b50\u5206\u7c7b\u63cf\u8ff0')),
                ('type_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WeeklyReport.BuildType', verbose_name='\u5206\u7c7b\u540d\u79f0')),
            ],
            options={
                'verbose_name': '\u56e2\u961f\u5efa\u8bbe\u5b50\u5206\u7c7b',
                'verbose_name_plural': '\u56e2\u961f\u5efa\u8bbe\u5b50\u5206\u7c7b\u7ba1\u7406',
            },
        ),
        migrations.CreateModel(
            name='SubProductType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_type_name', models.CharField(max_length=200, unique=True, verbose_name='\u4ea7\u54c1\u5b50\u5206\u7c7b\u540d\u79f0')),
                ('desc', models.CharField(blank=True, max_length=500, null=True, verbose_name='\u5b50\u5206\u7c7b\u63cf\u8ff0')),
                ('type_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WeeklyReport.ProductType', verbose_name='\u4ea7\u54c1\u5206\u7c7b\u540d\u79f0')),
            ],
            options={
                'verbose_name': '\u4ea7\u54c1\u5b50\u5206\u7c7b',
                'verbose_name_plural': '\u4ea7\u54c1\u5b50\u5206\u7c7b\u7ba1\u7406',
            },
        ),
        migrations.CreateModel(
            name='SummaryStatus',
            fields=[
                ('status', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='\u72b6\u6001\u540d\u79f0')),
                ('desc', models.TextField(blank=True, null=True, verbose_name='\u8be6\u7ec6\u63cf\u8ff0')),
            ],
            options={
                'verbose_name': '\u6c47\u603b\u72b6\u6001',
                'verbose_name_plural': '\u6c47\u603b\u72b6\u6001\u7ba1\u7406',
            },
        ),
        migrations.CreateModel(
            name='TeamBuilding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('people', models.CharField(max_length=300, verbose_name='\u4eba\u5458')),
                ('summarize', models.CharField(max_length=500, verbose_name='\u672c\u5468\u603b\u7ed3\u4e0e\u5f97\u5931')),
                ('next_week_plan', models.CharField(blank=True, max_length=500, null=True, verbose_name='\u4e0b\u5468\u8ba1\u5212')),
                ('stage_plan', models.CharField(blank=True, max_length=500, null=True, verbose_name='\u9636\u6bb5\u6027\u8ba1\u5212')),
                ('remark', models.CharField(blank=True, max_length=500, null=True, verbose_name='\u7279\u6b8a\u8bf4\u660e')),
                ('build_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WeeklyReport.BuildType', verbose_name='\u56e2\u961f\u5efa\u8bbe\u5206\u7c7b')),
                ('date_period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WeeklyReport.DatePeriod', verbose_name='\u65f6\u95f4\u5468\u671f')),
                ('depart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserAccess.Department', verbose_name='\u6240\u5c5e\u90e8\u95e8')),
                ('sub_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WeeklyReport.SubBuildType', verbose_name='\u56e2\u961f\u5efa\u8bbe\u5b50\u5206\u7c7b')),
            ],
            options={
                'verbose_name': '\u56e2\u961f\u5efa\u8bbe',
                'verbose_name_plural': '\u56e2\u961f\u5efa\u8bbe\u7ba1\u7406',
            },
        ),
        migrations.AddField(
            model_name='productdevelopment',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WeeklyReport.ProductType', verbose_name='\u4ea7\u54c1'),
        ),
        migrations.AddField(
            model_name='productdevelopment',
            name='sub_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WeeklyReport.SubProductType', verbose_name='\u5b50\u4ea7\u54c1'),
        ),
        migrations.AddField(
            model_name='personalreport',
            name='summary_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WeeklyReport.SummaryStatus', verbose_name='\u6c47\u603b\u72b6\u6001'),
        ),
        migrations.AddField(
            model_name='jobcode',
            name='job_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WeeklyReport.JobType', verbose_name='\u5de5\u4f5c\u7c7b\u522b'),
        ),
        migrations.AddField(
            model_name='jobcode',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WeeklyReport.ProjectStatus', verbose_name='\u9879\u76ee\u8fdb\u5ea6'),
        ),
    ]
