# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-20 06:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Asset', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetmanagement',
            name='life_cycle',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Asset.LifeCycle', verbose_name='\u751f\u547d\u5468\u671f'),
        ),
    ]
