# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-20 06:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Asset', '0002_auto_20180420_1440'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assetmanagement',
            name='life_cycle',
        ),
        migrations.AddField(
            model_name='lifecycle',
            name='asset',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='Asset.AssetManagement', verbose_name='\u5173\u8054\u8d44\u4ea7'),
            preserve_default=False,
        ),
    ]
