# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-26 03:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Asset', '0004_auto_20180420_1519'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assetrecord',
            options={'ordering': ['-id'], 'verbose_name': '\u4f7f\u7528\u8bb0\u5f55', 'verbose_name_plural': '\u4f7f\u7528\u8bb0\u5f55\u7ba1\u7406\u8868'},
        ),
        migrations.AddField(
            model_name='assetrecord',
            name='status',
            field=models.BooleanField(default=False, verbose_name='\u5ba1\u6838\u72b6\u6001'),
        ),
    ]
