# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-17 03:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('UserAccess', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Level',
            fields=[
                ('level', models.CharField(max_length=200, primary_key=True, serialize=False, verbose_name='\u7ea7\u522b')),
                ('desc', models.CharField(blank=True, max_length=1000, null=True, verbose_name='\u7ea7\u522b\u63cf\u8ff0')),
            ],
            options={
                'verbose_name': '\u7ea7\u522b',
                'verbose_name_plural': '\u7ea7\u522b\u7ba1\u7406\u8868',
            },
        ),
        migrations.CreateModel(
            name='Memorandum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateField(auto_now=True, verbose_name='\u521b\u5efa\u65e5\u671f')),
                ('content', models.TextField(verbose_name='\u5907\u5fd8\u5185\u5bb9')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='\u5907\u6ce8\u8bf4\u660e')),
            ],
            options={
                'verbose_name': '\u5907\u5fd8\u5f55',
                'verbose_name_plural': '\u5907\u5fd8\u5f55\u7ba1\u7406\u8868',
            },
        ),
        migrations.CreateModel(
            name='MemorandumStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='\u540d\u79f0')),
                ('desc', models.TextField(blank=True, null=True, verbose_name='\u63cf\u8ff0')),
            ],
            options={
                'verbose_name': '\u5907\u5fd8\u72b6\u6001',
                'verbose_name_plural': '\u5907\u5fd8\u72b6\u6001\u7ba1\u7406',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('send_user', models.CharField(default='\u7cfb\u7edf\u7ba1\u7406\u5458', max_length=100, verbose_name='\u53d1\u9001\u7528\u6237')),
                ('message', models.CharField(max_length=1000, verbose_name='\u6d88\u606f')),
                ('read_status', models.BooleanField(default=False, verbose_name='\u9605\u8bfb\u72b6\u6001')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DashBoard.Level', verbose_name='\u6d88\u606f\u7b49\u7ea7')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserAccess.MyUser', verbose_name='\u6240\u5c5e\u7528\u6237')),
            ],
            options={
                'ordering': ['-create_time'],
                'verbose_name': '\u6d88\u606f\u63d0\u793a',
                'verbose_name_plural': '\u6d88\u606f\u63d0\u793a\u7ba1\u7406\u8868',
            },
        ),
        migrations.CreateModel(
            name='UpdateType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='\u540d\u79f0')),
                ('desc', models.TextField(blank=True, null=True, verbose_name='\u63cf\u8ff0')),
            ],
            options={
                'verbose_name': '\u66f4\u65b0\u7c7b\u578b',
                'verbose_name_plural': '\u66f4\u65b0\u7c7b\u578b\u7ba1\u7406',
            },
        ),
        migrations.CreateModel(
            name='Version',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=200, unique=True, verbose_name='\u7248\u672c\u53f7')),
                ('deploy_time', models.DateField(verbose_name='\u53d1\u5e03\u65f6\u95f4')),
                ('desc', models.TextField(blank=True, null=True, verbose_name='\u7248\u672c\u63cf\u8ff0')),
            ],
            options={
                'ordering': ['-id'],
                'verbose_name': '\u7248\u672c',
                'verbose_name_plural': '\u7248\u672c\u7ba1\u7406',
            },
        ),
        migrations.CreateModel(
            name='VersionInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_info', models.TextField(verbose_name='\u66f4\u65b0\u8bb0\u5f55')),
                ('update_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DashBoard.UpdateType', verbose_name='\u66f4\u65b0\u7c7b\u578b')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DashBoard.Version', verbose_name='\u7248\u672c\u53f7')),
            ],
            options={
                'verbose_name': '\u66f4\u65b0\u8bb0\u5f55',
                'verbose_name_plural': '\u66f4\u65b0\u8bb0\u5f55\u7ba1\u7406',
            },
        ),
        migrations.CreateModel(
            name='WebsiteGuide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='\u7f51\u7ad9\u540d\u79f0')),
                ('url', models.CharField(max_length=100, verbose_name='\u7f51\u5740')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserAccess.MyUser', verbose_name='\u7528\u6237')),
            ],
            options={
                'verbose_name': '\u7f51\u7ad9\u5bfc\u822a',
                'verbose_name_plural': '\u7f51\u7ad9\u5bfc\u822a\u8868',
            },
        ),
        migrations.AddField(
            model_name='memorandum',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DashBoard.MemorandumStatus', verbose_name='\u72b6\u6001'),
        ),
        migrations.AddField(
            model_name='memorandum',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserAccess.MyUser', verbose_name='\u7528\u6237'),
        ),
    ]
