#!/usr/bin/env python
# coding:utf-8

from django.conf.urls import url
from WeeklyReport import views
from django.views.generic import TemplateView

urlpatterns = [
    url(r'^daily_report/$', views.daily_report, name="daily_report"),
    url(r'^daily_report/data/$', views.daily_report_data, name="daily_report_data"),
    url(r'^daily_report/trash/$', views.delete_report_data, name="delete_report_data"),
    url(r'^daily_report/add/$', views.daily_report_add, name="daily_report_add"),
    url(r'^daily_report/add_form/$',
        TemplateView.as_view(template_name="weekly_report/template/daily_report_add_form.html"),
        name="daily_report_add_form"),
    url(r'^daily_repoprt/modify/$', views.daily_report_modify, name="daily_report_modify"),
    url(r'^job_type/get/$', views.job_type_get, name="job_type_get"),
    url(r'^username/get/$', views.username_get, name="username_get"),
    url(r'^depart/get/$', views.depart_get, name="depart_get"),
    url(r'^job_code/get/$', views.job_code_get, name="job_code_get"),
    url(r'^job_status/get/$', views.job_status_get, name="job_status_get"),
    url(r'^date_period/get/$', views.date_period_get, name="date_period_get"),
    url(r'^daily_report/delete/$', views.daily_report_delete, name="daily_report_delete"),
    url(r'^build_type/get/$', views.build_type_get, name="build_type_get"),
    url(r'^sub_build_type/get/$', views.sub_build_type_get, name="sub_type_get"),
    url(r'^weekly_report/get/$', views.weekly_report_get, name="weekly_report_get"),
    url(r'^project/get/$', views.project_get, name="project_get"),
    url(r'^plan_report/add_form/$', views.plan_report_add_form, name="plan_report_add_form"),
    url(r'^plan_report/add/$', views.plan_report_add, name="plan_report_add"),
    url(r'^plan_report/get/$', views.plan_report_get, name="plan_report_get"),
    url(r'^plan_report/delete/$', views.plan_report_delete, name="plan_report_delete"),
    url(r'^report_summary/$', TemplateView.as_view(template_name="weekly_report/template/report_summary.html"),
        name="report_summary"),
    url(r'^report_summary/daily_report/get/$', views.daily_summary_get, name="daily_summary_get"),
    url(r'^report_summary/plan_report/get/$', views.plan_summary_get, name="plan_summary_get"),
    url(r'^report_summary/daily_report/audit/$', views.daily_report_audit, name="daily_report_audit"),
    url(r'^report_summary/daily_report/audit/batch/$', views.daily_report_audit_batch, name="daily_report_audit_batch"),
    url(r'^report_summary/sell_project/get/$', views.sell_project_get, name="sell_project_get"),
    url(r'^report_summary/this_week/get/$', views.this_week_get, name="this_week_get"),
    url(r'^report_summary/summary_status/get/$', views.summary_status_get, name="summary_status_get"),
    url(r'^report_summary/product_development/add_form/$',
        TemplateView.as_view(template_name="weekly_report/template/product_development_add_form.html"),
        name="product_development_add_form"),
    url(r'^report_summary/product_type/get/$', views.product_type_get, name="product_type_get"),
    url(r'^report_summary/sub_product/get/$', views.sub_product_get, name="sub_product_get"),
    url(r'^report_summary/product_development/add/$', views.product_development_add, name="product_development_add"),
    url(r'^report_summary/product_development/get/$', views.product_development_get, name="product_development_get"),
    url(r'^report_summary/product_development/delete_table/$',
        TemplateView.as_view(template_name="weekly_report/template/delete_product_development.html"),
        name="product_development_table"),
    url(r'^report_summary/product_development/table_get/$',
        views.product_development_table_get, name="product_development_table_get"),
    url(r'report_summary/product_development/delete/$', views.product_development_delete,
        name="product_development_delete"),
    url(r'report_summary/strategic_deployment/get/$', views.strategic_deployment_get, name="strategic_deployment_get"),
    url(r'report_summary/strategic_deployment/delete/$', views.strategic_deployment_delete,
        name="strategic_deployment_delete"),
    url(r'^report_summary/strategic_deployment/add_form/$',
        TemplateView.as_view(template_name="weekly_report/template/strategic_deployment_table.html"),
        name="strategic_deployment_add_form"),
    url(r'^report_summary/strategic_deployment/add/$', views.strategic_deployment_add, name="strategic_deployment_add"),
    url(r'^report_summary/strategic_deployment/delete_table/$',
        TemplateView.as_view(template_name="weekly_report/template/strategic_deployment_delete_table.html"),
        name="strategic_deployment_delete_table"),
    url(r'^report_summary/strategic_deployment/table_get/$', views.strategic_deployment_table_get,
        name="strategic_deployment_table_get"),
    url(r'^report_summary/team_building/get/$', views.team_building_get, name="team_building_get"),
    url(r'^report_summary/team_building/add_form/$',
        TemplateView.as_view(template_name="weekly_report/template/team_building_add_form.html"),
        name="team_building_add_form"),
    url(r'^report_summary/team_building/add/$', views.team_building_add, name="team_building_add"),
    url(r'^report_summary/team_building/delete_table/$',
        TemplateView.as_view(template_name="weekly_report/template/team_building_delete_table.html"),
        name="team_building_delete_table"),
    url(r'^report_summary/team_building/table_get/$', views.team_building_table_get, name="team_building_table_get"),
    url(r'^report_summary/team_building/delete/$', views.team_building_delete, name="team_building_delete"),
    url(r'^advanced_setting/$', TemplateView.as_view(template_name="weekly_report/template/advanced_setting.html"),
        name="advanced_setting"),
    url(r'^report_summary/weekly_report/export/$', views.export_weekly_report, name="export_weekly_report"),
    url(r'^advanced_setting/job_code/add_form/$', views.job_code_add_form, name="job_code_add_form"),
    url(r'^advanced_setting/job_code/add/$', views.job_code_add, name="job_code_add"),
    url(r'^advanced_setting/job_code/delete/$', views.job_code_delete, name="job_code_delete"),
    url(r'^advanced_setting/product_type/add_form/$', views.product_type_add_form, name="product_type_add_form"),
    url(r'^advanced_setting/sub_product/add_form/$', views.sub_product_add_form, name="sub_product_add_form"),
    url(r'^advanced_setting/product_type/add/$', views.product_type_add, name="product_type_add"),
    url(r'^advanced_setting/sub_product/add/$', views.sub_product_add, name="sub_product_add"),
    url(r'^advanced_setting/product_type/delete/$', views.product_type_delete, name="product_type_delete"),
    url(r'^advanced_setting/sub_product/delete/$', views.sub_product_delete, name="sub_product_delete"),
    url(r'^advanced_setting/job_code/upload/$', views.job_code_upload, name="job_code_upload"),
    url(r'^daily_report/export/$', views.export_daily_report, name="export_daily_report"),
]
