# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-17 03:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('UserAccess', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classify',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='\u540d\u79f0')),
                ('desc', models.TextField(blank=True, null=True, verbose_name='\u63cf\u8ff0')),
            ],
            options={
                'verbose_name': '\u914d\u7f6e\u6587\u4ef6\u5206\u7c7b',
                'verbose_name_plural': '\u914d\u7f6e\u6587\u4ef6\u5206\u7c7b\u7ba1\u7406',
            },
        ),
        migrations.CreateModel(
            name='Distro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='\u7cfb\u7edf\u955c\u50cf')),
                ('desc', models.TextField(blank=True, null=True, verbose_name='\u63cf\u8ff0\u8bf4\u660e')),
            ],
        ),
        migrations.CreateModel(
            name='Kickstart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='ks\u540d\u79f0')),
                ('content', models.TextField(verbose_name='KS\u6587\u4ef6\u5185\u5bb9')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('desc', models.TextField(blank=True, null=True, verbose_name='\u63cf\u8ff0\u8bf4\u660e')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserAccess.MyUser', verbose_name='\u6240\u5c5e\u8005')),
            ],
            options={
                'verbose_name': 'ks\u914d\u7f6e\u6587\u4ef6',
                'verbose_name_plural': 'ks\u914d\u7f6e\u6587\u4ef6\u7ba1\u7406',
            },
        ),
        migrations.CreateModel(
            name='LogRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.TextField(verbose_name='\u64cd\u4f5c\u65e5\u5fd7')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
            ],
            options={
                'verbose_name': '\u704c\u88c5\u65e5\u5fd7',
                'verbose_name_plural': '\u704c\u88c5\u65e5\u5fd7\u7ba1\u7406',
            },
        ),
        migrations.CreateModel(
            name='Privilege',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateField(verbose_name='\u5f00\u59cb\u65f6\u95f4')),
                ('end_time', models.DateField(verbose_name='\u7ed3\u675f\u65f6\u95f4')),
            ],
            options={
                'verbose_name': '\u6388\u6743',
                'verbose_name_plural': '\u6388\u6743\u7ba1\u7406',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='\u914d\u7f6e\u540d\u79f0')),
                ('desc', models.CharField(blank=True, max_length=200, null=True, verbose_name='\u63cf\u8ff0')),
                ('create_time', models.DateField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('distro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cobbler.Distro', verbose_name='\u7cfb\u7edf\u955c\u50cf')),
                ('ks', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cobbler.Kickstart', verbose_name='ks\u6587\u4ef6')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserAccess.MyUser', verbose_name='\u6240\u6709\u8005')),
            ],
            options={
                'verbose_name': '\u914d\u7f6e\u6587\u4ef6',
                'verbose_name_plural': '\u914d\u7f6e\u6587\u4ef6\u7ba1\u7406',
            },
        ),
        migrations.CreateModel(
            name='System',
            fields=[
                ('ip', models.GenericIPAddressField(primary_key=True, serialize=False, verbose_name='IP\u5730\u5740')),
                ('mac', models.CharField(max_length=100, unique=True, verbose_name='MAC\u5730\u5740')),
                ('nic', models.CharField(max_length=100, verbose_name='\u7f51\u53e3\u540d\u79f0')),
                ('usage', models.CharField(default='\u672a\u586b', max_length=255, verbose_name='\u673a\u5668\u7528\u9014')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('desc', models.CharField(blank=True, max_length=200, null=True, verbose_name='\u63cf\u8ff0')),
                ('netboot', models.BooleanField(default=False, verbose_name='\u542f\u7528\u72b6\u6001')),
                ('status', models.BooleanField(default=False, verbose_name='\u5ba1\u6838\u72b6\u6001')),
                ('person_in_charge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserAccess.MyUser', verbose_name='\u8d23\u4efb\u4eba')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cobbler.Profile', verbose_name='\u914d\u7f6e\u6587\u4ef6')),
            ],
            options={
                'verbose_name': '\u673a\u5668\u5b9e\u4f8b',
                'verbose_name_plural': '\u673a\u5668\u5b9e\u4f8b\u7ba1\u7406',
            },
        ),
        migrations.AddField(
            model_name='privilege',
            name='system',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cobbler.System', verbose_name='\u673a\u5668\u5b9e\u4f8b'),
        ),
        migrations.AddField(
            model_name='privilege',
            name='target_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserAccess.MyUser', verbose_name='\u6388\u6743\u7528\u6237'),
        ),
        migrations.AddField(
            model_name='logrecord',
            name='system',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cobbler.System', verbose_name='\u673a\u5668\u5b9e\u4f8b'),
        ),
        migrations.AddField(
            model_name='logrecord',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserAccess.MyUser', verbose_name='\u64cd\u4f5c\u7528\u6237'),
        ),
    ]
