# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-17 03:47
from __future__ import unicode_literals

import UserAccess.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('depart', models.CharField(max_length=200, unique=True, verbose_name='\u90e8\u95e8\u540d\u79f0')),
                ('desc', models.TextField(blank=True, null=True, verbose_name='\u90e8\u95e8\u7b80\u4ecb')),
            ],
            options={
                'verbose_name': '\u90e8\u95e8',
                'verbose_name_plural': '\u90e8\u95e8\u7ba1\u7406',
            },
        ),
        migrations.CreateModel(
            name='LoginRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_ip', models.CharField(max_length=50, verbose_name='\u767b\u5f55IP')),
                ('login_time', models.DateTimeField(blank=True, null=True, verbose_name='\u767b\u5f55\u65f6\u95f4')),
                ('login_exit_time', models.DateTimeField(blank=True, null=True, verbose_name='\u9000\u51fa\u65f6\u95f4')),
            ],
            options={
                'ordering': ['-login_time'],
                'verbose_name': '\u767b\u5f55\u8bb0\u5f55',
                'verbose_name_plural': '\u767b\u5f55\u8bb0\u5f55\u7ba1\u7406',
            },
        ),
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, unique=True, verbose_name='\u7528\u6237\u540d')),
                ('password', models.CharField(max_length=100, verbose_name='\u5bc6\u7801')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='\u90ae\u7bb1')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('modify_time', models.DateTimeField(auto_now=True, verbose_name='\u4fee\u6539\u65f6\u95f4')),
                ('use', models.BooleanField(default=False, verbose_name='\u542f\u7528\u72b6\u6001')),
                ('depart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserAccess.Department', verbose_name='\u90e8\u95e8')),
            ],
            options={
                'verbose_name': '\u7528\u6237',
                'verbose_name_plural': '\u7528\u6237\u7ba1\u7406',
            },
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission_name', models.CharField(max_length=50, unique=True, verbose_name='\u6743\u9650\u540d\u79f0')),
                ('permission_value', models.CharField(max_length=50, unique=True, verbose_name='\u6743\u9650\u5c5e\u6027')),
                ('permission_detail', models.TextField(blank=True, null=True, verbose_name='\u6743\u9650\u63cf\u8ff0')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('modify_time', models.DateTimeField(auto_now=True, verbose_name='\u4fee\u6539\u65f6\u95f4')),
            ],
            options={
                'verbose_name': '\u6743\u9650',
                'verbose_name_plural': '\u6743\u9650\u7ba1\u7406',
            },
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_name', models.CharField(max_length=20, unique=True, verbose_name='\u89d2\u8272\u540d\u79f0')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('modify_time', models.DateTimeField(auto_now=True, verbose_name='\u4fee\u6539\u65f6\u95f4')),
                ('permission', models.ManyToManyField(blank=True, to='UserAccess.Permission', verbose_name='\u89d2\u8272\u6743\u9650')),
            ],
            options={
                'verbose_name': '\u89d2\u8272',
                'verbose_name_plural': '\u89d2\u8272\u7ba1\u7406',
            },
        ),
        migrations.CreateModel(
            name='UserGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=100, unique=True, verbose_name='\u7ec4\u540d\u79f0')),
                ('group_desc', models.TextField(blank=True, null=True, verbose_name='\u7ec4\u63cf\u8ff0')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('modify_time', models.DateTimeField(auto_now=True, verbose_name='\u4fee\u6539\u65f6\u95f4')),
                ('group_permission', models.ManyToManyField(to='UserAccess.Permission', verbose_name='\u7ec4\u6743\u9650')),
                ('group_user', models.ManyToManyField(to='UserAccess.MyUser', verbose_name='\u7ec4\u6210\u5458')),
            ],
            options={
                'verbose_name': '\u7528\u6237\u7ec4',
                'verbose_name_plural': '\u7528\u6237\u7ec4\u7ba1\u7406',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('introduce', models.CharField(blank=True, max_length=500, null=True, verbose_name='\u4e2a\u4eba\u7b80\u4ecb')),
                ('phone', models.IntegerField(blank=True, null=True, verbose_name='\u8054\u7cfb\u7535\u8bdd')),
                ('avatar', models.ImageField(default='avatar/default/default.png', upload_to=UserAccess.models.image_filepath, verbose_name='\u5934\u50cf')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='UserAccess.MyUser', verbose_name='\u6240\u5c5e\u7528\u6237')),
            ],
            options={
                'verbose_name': '\u7528\u6237\u914d\u7f6e',
                'verbose_name_plural': '\u7528\u6237\u914d\u7f6e\u7ba1\u7406',
            },
        ),
        migrations.AddField(
            model_name='myuser',
            name='role',
            field=models.ManyToManyField(to='UserAccess.Roles', verbose_name='\u89d2\u8272'),
        ),
        migrations.AddField(
            model_name='loginrecord',
            name='login_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserAccess.MyUser', verbose_name='\u767b\u5f55\u7528\u6237'),
        ),
    ]
